[package]
name = "rosalind"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0"
num-traits = "0.2"
ureq = "2.2"
itertools = "0.10"

[dev-dependencies]
maplit = "1.0"
